"""Utility to convert gen.Chunk objects to RawCircuitLayer instances.

This module provides functionality to convert between Gidney's chunk-based 
approach and TQEC's layer architecture, enabling integration of circuits
generated by the gen framework into TQEC's compilation system.
"""

from __future__ import annotations

import stim
from typing import Dict, Callable

from tqec.circuit.schedule.circuit import ScheduledCircuit
from tqec.compile.blocks.layers.atomic.raw import RawCircuitLayer
from tqec.compile.specs.library.generators import gen
from tqec.utils.scale import LinearFunction, PhysicalQubitScalable2D


def extract_shape_from_chunk(chunk: gen.Chunk) -> PhysicalQubitScalable2D:
    """Extract scalable shape information from a chunk's qubit coordinates.
    
    Args:
        chunk: The chunk containing complex coordinate -> qubit index mapping
        
    Returns:
        PhysicalQubitScalable2D representing the shape of the circuit
        
    Notes:
        Complex coordinates in gen follow the pattern:
        - Data qubits: x + 1j*y for x,y in range(distance)  
        - Measurement qubits: data_qubit + offset (e.g., 0.5+0.5j)
        - The distance parameter controls the grid size
    """
    if not chunk.q2i:
        # Empty chunk - return minimal shape
        return PhysicalQubitScalable2D(
            LinearFunction(0, 1),  # width = 1
            LinearFunction(0, 1)   # height = 1
        )
    
    coords = list(chunk.q2i.keys())
    
    # Extract bounds from complex coordinates
    real_coords = [q.real for q in coords]
    imag_coords = [q.imag for q in coords]
    
    min_real, max_real = min(real_coords), max(real_coords) 
    min_imag, max_imag = min(imag_coords), max(imag_coords)
    
    # Calculate width and height from coordinate bounds
    # Add 1 to convert from max coordinate to grid size
    width = int(max_real - min_real) + 1
    height = int(max_imag - min_imag) + 1
    
    # For gen chunks, the shape typically doesn't scale with k
    # The distance parameter is fixed when the chunk is created
    return PhysicalQubitScalable2D(
        LinearFunction(0, width),   # slope=0, offset=width (constant width)
        LinearFunction(0, height)   # slope=0, offset=height (constant height)
    )


def count_moments_in_stim_circuit(circuit: stim.Circuit) -> int:
    """Count the number of moments (time steps) in a stim circuit.
    
    Args:
        circuit: The stim circuit to analyze
        
    Returns:
        Number of moments in the circuit
        
    Notes:
        Moments are separated by TICK instructions. The circuit starts
        with an implicit moment, so the count is 1 + number of TICKs.
    """
    tick_count = 0
    for instruction in circuit:
        if isinstance(instruction, stim.CircuitRepeatBlock):
            # Count TICKs in repeat blocks
            body_ticks = 0
            for body_instruction in instruction.body_copy():
                if body_instruction.name == 'TICK':
                    body_ticks += 1
            tick_count += body_ticks * instruction.repeat_count
        elif instruction.name == 'TICK':
            tick_count += 1
    
    # Add 1 for the initial implicit moment
    return tick_count + 1


def create_scaling_circuit_factory(chunk: gen.Chunk) -> Callable[[int], ScheduledCircuit]:
    """Create a circuit factory function that handles scaling parameter k.
    
    Args:
        chunk: The source chunk containing the base circuit
        
    Returns:
        A function that takes scaling parameter k and returns ScheduledCircuit
        
    Notes:
        Since gen chunks are created with fixed distance, this factory
        ignores the scaling parameter k and always returns the same circuit.
        Future implementations could support actual scaling.
    """
    def circuit_factory(k: int) -> ScheduledCircuit:
        # Create a new circuit with integer coordinates mapped from fractional ones
        # TQEC expects integer coordinates, but gen uses fractional ones for ancilla qubits
        remapped_circuit = stim.Circuit()
        
        for instruction in chunk.circuit:
            if isinstance(instruction, stim.CircuitInstruction):
                if instruction.name == 'QUBIT_COORDS':
                    # Convert fractional coordinates to integers
                    gate_args = instruction.gate_args_copy()
                    targets = instruction.targets_copy()
                    
                    if len(gate_args) >= 2:
                        x, y = gate_args[0], gate_args[1]
                        # Map fractional coordinates to integers by scaling and offsetting
                        # Scale by 2 and add offset to ensure all coordinates are positive integers
                        int_x = int(x * 2 + 10)
                        int_y = int(y * 2 + 10)
                        remapped_circuit.append('QUBIT_COORDS', targets, [int_x, int_y])
                    else:
                        # Keep original if not enough arguments
                        remapped_circuit.append(instruction.name, targets, gate_args)
                else:
                    # Copy other instructions as-is
                    targets = instruction.targets_copy()
                    gate_args = instruction.gate_args_copy()
                    if instruction.name == 'TICK':
                        # TICK has no targets or args, just append the name
                        remapped_circuit.append('TICK')
                    else:
                        remapped_circuit.append(instruction.name, targets, gate_args)
            elif isinstance(instruction, stim.CircuitRepeatBlock):
                # Handle repeat blocks recursively
                remapped_circuit.append(instruction)
            else:
                # Handle other instructions like TICK
                remapped_circuit.append(instruction.name if hasattr(instruction, 'name') else str(instruction))
        
        return ScheduledCircuit.from_circuit(remapped_circuit)
    
    return circuit_factory


def chunk_to_raw_circuit(chunk: gen.Chunk) -> RawCircuitLayer:
    """Convert a gen.Chunk to a RawCircuitLayer.
    
    Args:
        chunk: The chunk to convert
        
    Returns:
        RawCircuitLayer instance equivalent to the input chunk
        
    Example:
        ```python
        # Create a chunk using gen framework
        patch = gen.surface_code_patch(distance=3)
        chunk = gen.standard_surface_code_chunk(patch)
        
        # Convert to RawCircuitLayer
        layer = chunk_to_raw_circuit(chunk)
        
        # Use in TQEC compilation
        block = Block([layer])
        ```
    """
    # 1. Extract shape information from qubit coordinates
    shape = extract_shape_from_chunk(chunk)
    
    # 2. Count moments in the circuit
    num_moments = count_moments_in_stim_circuit(chunk.circuit)
    moments_function = LinearFunction(0, num_moments)  # Constant number of moments
    
    # 3. Create scaling circuit factory
    circuit_factory = create_scaling_circuit_factory(chunk)
    
    # 4. Create and return RawCircuitLayer
    return RawCircuitLayer(
        circuit_factory=circuit_factory,
        scalable_raw_shape=shape,
        scalable_num_moments=moments_function
    )


def chunk_to_scalable_raw_circuit(
    chunk_generator: Callable[[int], gen.Chunk],
    base_distance: int = 3
) -> RawCircuitLayer:
    """Convert a chunk generator function to a RawCircuitLayer with true scaling.
    
    Args:
        chunk_generator: Function that takes distance and returns a chunk
        base_distance: Base distance to use for shape extraction
        
    Returns:
        RawCircuitLayer that properly scales with parameter k
        
    Example:
        ```python
        # Define a chunk generator
        def make_surface_code_chunk(distance: int) -> gen.Chunk:
            patch = gen.surface_code_patch(distance=distance)
            return gen.standard_surface_code_chunk(patch)
        
        # Convert to scalable RawCircuitLayer
        layer = chunk_to_scalable_raw_circuit(make_surface_code_chunk)
        ```
    """
    # Generate base chunk to extract shape pattern
    base_chunk = chunk_generator(base_distance)
    
    # Extract shape pattern - assume linear scaling with distance
    # For surface codes: distance d → (2d-1) x (2d-1) grid typically
    base_shape = extract_shape_from_chunk(base_chunk)
    
    # Create scalable shape - assumes shape scales linearly with k
    # This may need adjustment based on specific chunk type
    scalable_shape = PhysicalQubitScalable2D(
        LinearFunction(base_shape.x(1) / base_distance, 0),  # slope = width/distance
        LinearFunction(base_shape.y(1) / base_distance, 0)   # slope = height/distance  
    )
    
    # Moments typically scale with distance for surface codes
    base_moments = count_moments_in_stim_circuit(base_chunk.circuit)
    moments_function = LinearFunction(base_moments / base_distance, 0)
    
    def scaling_circuit_factory(k: int) -> ScheduledCircuit:
        """Generate circuit for scaling parameter k."""
        scaled_distance = base_distance * k if k > 0 else base_distance
        scaled_chunk = chunk_generator(scaled_distance)
        return ScheduledCircuit.from_circuit(scaled_chunk.circuit)
    
    return RawCircuitLayer(
        circuit_factory=scaling_circuit_factory,
        scalable_raw_shape=scalable_shape,
        scalable_num_moments=moments_function
    )